version: "3.7"

services:
  app:
    image: python:3.7-slim-stretch
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ../:/home/app

    command: >
      bash -c "python3 app/main.py"


